# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4f52998907a7d3317663c4fa7bc2a7781ef3df76d6d7dc3f931e741730066186578f2123ff3dbfd6220d2c212655020b740379d5cf4a0e7613a02fd146332ce7

test:
  secret_key_base: 3c4294d7614e91d9cd71ef2d29f3cca199219b5b3f773baed6db77dbd3ffa605f438fa5fc6f5ac3f7cb7f68a8e0bd8f673ab5df973620c56b9f36a8ead7a1d06

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
